[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect all traffic to HTTPS
[[redirects]]
  from = "http://floorplay.agency/*"
  to = "https://floorplay.agency/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.floorplay.agency/*"
  to = "https://floorplay.agency/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.floorplay.agency/*"
  to = "https://floorplay.agency/:splat"
  status = 301
  force = true

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "frame-ancestors 'self' https://sanity.io https://www.sanity.io https://*.sanity.io https://*.sanity.build"
